### ISSUE TITLE
snapshotView cannot created in iOS10

### ISSUE THREAD

**Issue by Demons-Bee** [Vict0rS/LUNTabBarController#1]
![simulator screen shot sep 22 2016 11 49 06](https://cloud.githubusercontent.com/assets/6848088/18737842/bd18be6c-80c8-11e6-8f53-cdbab30be616.png)

**Comment by Demons-Bee** [comment]
There is a [comment](https://forums.developer.apple.com/thread/63307) from Apple Developer Forums

**Comment by Vict0rS** [comment]
Fixed in 1.0.3 release. Thank you for your feedback.
